export const dynamic = 'force-dynamic';

import { NextResponse }       from 'next/server';
import { createClient }       from '../../../../lib/supabase-server';
import { createAdminClient }  from '../../../../lib/supabase-admin';
import { sendInterviewEmail } from '../../../../lib/email';

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://aarem-lms.vercel.app';

function guard(user) {
  return !user || user.user_metadata?.role !== 'super_admin';
}

function fmtDate(iso) {
  const [y, m, d] = iso.split('-');
  const months = ['يناير','فبراير','مارس','أبريل','مايو','يونيو',
                  'يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];
  return `${parseInt(d)} ${months[parseInt(m) - 1]} ${y}`;
}

// GET — list interviews; optional ?date=YYYY-MM-DD&interviewer=NAME for conflict check
export async function GET(req) {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (guard(user)) return NextResponse.json({ error: 'غير مخول' }, { status: 403 });

  const { searchParams } = new URL(req.url);
  const date        = searchParams.get('date');
  const interviewer = searchParams.get('interviewer');

  const admin = createAdminClient();
  let q = admin
    .from('interviews')
    .select('id, application_id, interviewer_name, interview_date, start_time, candidate_response, reschedule_reason, created_at')
    .order('created_at', { ascending: false });

  if (date)        q = q.eq('interview_date', date);
  if (interviewer) q = q.eq('interviewer_name', interviewer);

  const { data, error } = await q;
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ interviews: data ?? [] });
}

// POST — schedule interview and send invitation email
export async function POST(req) {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (guard(user)) return NextResponse.json({ error: 'غير مخول' }, { status: 403 });

  let body;
  try { body = await req.json(); }
  catch { return NextResponse.json({ error: 'بيانات غير صالحة' }, { status: 400 }); }

  const { application_id, interviewer_name, interview_date, start_time } = body;
  if (!application_id || !interviewer_name || !interview_date || !start_time) {
    return NextResponse.json({ error: 'جميع الحقول مطلوبة' }, { status: 400 });
  }

  const admin = createAdminClient();

  // Conflict check: same interviewer + same date + same start_time slot
  const { data: clash } = await admin
    .from('interviews')
    .select('id')
    .eq('interviewer_name', interviewer_name)
    .eq('interview_date',   interview_date)
    .eq('start_time',       start_time)
    .limit(1);

  if (clash?.length) {
    return NextResponse.json(
      { error: 'هذا الوقت محجوز مسبقاً للمقابِل نفسه — اختر وقتاً آخر' },
      { status: 409 }
    );
  }

  // Fetch candidate name + email
  const { data: app, error: appErr } = await admin
    .from('recruitment_applications')
    .select('name, email')
    .eq('id', application_id)
    .single();

  if (appErr || !app) return NextResponse.json({ error: 'المترشح غير موجود' }, { status: 404 });

  // Insert interview row — response_token generated by DB default
  const { data: iv, error: insertErr } = await admin
    .from('interviews')
    .insert({ application_id, interviewer_name, interview_date, start_time })
    .select()
    .single();

  if (insertErr) return NextResponse.json({ error: insertErr.message }, { status: 500 });

  // Send invitation email
  const token       = iv.response_token;
  const confirmUrl  = `${APP_URL}/api/interview/respond?token=${token}&action=confirm`;
  const rejectUrl   = `${APP_URL}/api/interview/respond?token=${token}&action=reject`;
  const reschedUrl  = `${APP_URL}/interview/reschedule?token=${token}`;
  const timeLabel   = start_time.slice(0, 5);

  let emailSent = false;
  try {
    await sendInterviewEmail({
      to:              app.email,
      candidateName:   app.name,
      interviewerName: interviewer_name,
      dateStr:         fmtDate(interview_date),
      startTime:       timeLabel,
      confirmUrl,
      rescheduleUrl:   reschedUrl,
      rejectUrl,
    });
    emailSent = true;
  } catch (e) {
    console.error('[interviews] email failed:', e.message);
  }

  return NextResponse.json({ interview: iv, emailSent }, { status: 201 });
}

// DELETE — cancel / remove an interview
export async function DELETE(req) {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (guard(user)) return NextResponse.json({ error: 'غير مخول' }, { status: 403 });

  let body;
  try { body = await req.json(); }
  catch { return NextResponse.json({ error: 'بيانات غير صالحة' }, { status: 400 }); }

  const { id } = body;
  if (!id) return NextResponse.json({ error: 'معرّف غير صالح' }, { status: 400 });

  const admin = createAdminClient();
  const { error } = await admin.from('interviews').delete().eq('id', id);
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ success: true });
}
