'use client';
import { useEffect, useRef, useState } from 'react';
import { useRouter }                    from 'next/navigation';
import Link                             from 'next/link';
import { createClient }                 from '../../lib/supabase';
import Navbar                           from '../../components/Navbar';
import AssessmentCodes                  from '../../components/AssessmentCodes';
import StudentCodes                     from '../../components/StudentCodes';
import TeacherCodes                     from '../../components/TeacherCodes';
import GroupsManager                    from '../../components/GroupsManager';
import LessonLogbookView               from '../../components/LessonLogbookView';
import TeacherSpace                    from '../../components/TeacherSpace';
import NotificationBell                from '../../components/NotificationBell';
import FinancialsTab                   from '../../components/FinancialsTab';
import LifeSceneSimulator              from '../../components/LifeSceneSimulator';
import { useLanguage }                  from '../../contexts/LanguageContext';